name: Odoo OCI build and push

on:
  push:
    branches:
      - feature-*
      - 15-*
      - otbm

env:
  REGISTRY_HOST: ${{ gitea.registry_host }}
  REGISTRY_USERNAME: ${{ gitea.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.PAT }}
  APT_CACHER_NG: ${{ vars.APT_CACHER_NG }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ vars.REGISTRY_HOST }}/${{ gitea.repository_owner }}/bullseye-odoo15-base
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to private registry
        uses: https://github.com/docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Set up Docker Buildx
        uses: https://github.com/docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            APT_CACHER_NG=${{ vars.APT_CACHER_NG }}
          context: "{{defaultContext}}:15.0" # context:path
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
